version: '3.8'
services:
  java-maven-app:
    image: kvnvna/demo-app:java-maven-aws-1.0
    ports:
      - 8080:8080
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
